'use client';

import React from 'react';
import Link from 'next/link';
import Footer from '../components/Footer';

export default function TermsAndConditions() {
  return (
    <>
      <div className="min-h-screen bg-gray-900 text-white py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto bg-gray-800 p-8 rounded-lg shadow">
          <nav className="mb-8">
            <Link href="/" className="text-blue-400 hover:text-blue-300 transition-colors">
              &larr; Back to Home
            </Link>
          </nav>
          
          <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
          
          <div className="prose prose-invert max-w-none">
            <p className="mb-4 text-gray-300">Last Updated: {new Date().toLocaleDateString()}</p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3 text-gray-100">1. Introduction</h2>
            <p className="text-gray-300">
              Welcome to our AI Image Generator. These terms and conditions outline the rules and regulations for the use of our website.
              By accessing this website, we assume you accept these terms and conditions in full. Do not continue to use our website if you do not accept all of the terms and conditions stated on this page.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3 text-gray-100">2. License to Use</h2>
            <p className="text-gray-300">
              Unless otherwise stated, we own the intellectual property rights for all material on this website. All intellectual property rights are reserved.
              You may view and/or print pages from the website for your own personal use subject to restrictions set in these terms and conditions.
            </p>
            
            <h3 className="text-lg font-medium mt-4 mb-2 text-gray-200">You must not:</h3>
            <ul className="list-disc pl-6 mb-4 text-gray-300">
              <li>Republish material from this website</li>
              <li>Sell, rent or sub-license material from this website</li>
              <li>Reproduce, duplicate or copy material from this website</li>
              <li>Redistribute content from this website</li>
            </ul>
            
            <h2 className="text-xl font-semibold mt-6 mb-3 text-gray-100">3. User Content</h2>
            <p className="text-gray-300">
              In these terms and conditions, "User Content" means material (including without limitation text, images, audio material, video material and audio-visual material) that you submit to this website, for whatever purpose.
            </p>
            <p className="mt-2 text-gray-300">
              You grant to us a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, adapt, publish, translate and distribute your User Content in any existing or future media. You also grant to us the right to sub-license these rights, and the right to bring an action for infringement of these rights.
            </p>
            <p className="mt-2 text-gray-300">
              Your User Content must not be illegal or unlawful, must not infringe any third party's legal rights, and must not be capable of giving rise to legal action whether against you or us or a third party (in each case under any applicable law).
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3 text-gray-100">4. AI-Generated Content</h2>
            <p className="text-gray-300">
              The images generated by our AI service are provided "as is" without any warranties, expressed or implied. We do not guarantee that the generated content will be error-free, appropriate for any specific purpose, or non-infringing of third-party rights.
            </p>
            <p className="mt-2 text-gray-300">
              You are solely responsible for how you use the AI-generated images. We are not liable for any consequences resulting from your use of the generated content.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3 text-gray-100">5. Limitation of Liability</h2>
            <p className="text-gray-300">
              To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website (including, without limitation, any warranties implied by law in respect of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill).
            </p>
            <p className="mt-2 text-gray-300">
              Nothing in this disclaimer will:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-300">
              <li>Limit or exclude our or your liability for death or personal injury resulting from negligence</li>
              <li>Limit or exclude our or your liability for fraud or fraudulent misrepresentation</li>
              <li>Limit any of our or your liabilities in any way that is not permitted under applicable law</li>
              <li>Exclude any of our or your liabilities that may not be excluded under applicable law</li>
            </ul>
            
            <h2 className="text-xl font-semibold mt-6 mb-3 text-gray-100">6. Changes to These Terms</h2>
            <p className="text-gray-300">
              We may revise these terms of use at any time by amending this page. Please check this page regularly to ensure you are familiar with the current version.
            </p>
            
            <h2 className="text-xl font-semibold mt-6 mb-3 text-gray-100">7. Contact Us</h2>
            <p className="text-gray-300">
              If you have any questions about these Terms and Conditions, please contact us at:
            </p>
            <p className="mt-2">
              <Link href="/contact" className="text-blue-400 hover:text-blue-300 transition-colors">
                Contact Page
              </Link>
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
} 